export const environment = {
    utagInfo: {
        startQuestionnaire: {
            page_category: 'start-questionnaire | Recomendador',  
            page_name: 'start-questionnaire',
            page_section: 'home',
            page_subCategory: 'targeted',
            site_country: 'br',
            site_currencyCode: 'brl',  
            site_language: 'pt',  
            //site_prefix: 'amway',
            //site_region: 'americas', 
            //site_subRegion: 'latam', 
            //site_type: 'desktop',  
            //site_type_short: 'web', 
            //site_webProperty: 'nutrilite recommender',  
            //site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
        },
        howDoesItWork: {
            page_category: 'how-does-it-work | Recomendador',  
            page_name: 'how-does-it-work',
            page_section: 'how-does-it-work',
            page_subCategory: 'targeted',
            site_country: 'br',
            site_currencyCode: 'brl',  
            site_language: 'pt',  
            // site_prefix: 'amway',
            // site_region: 'americas', 
            // site_subRegion: 'latam', 
            // site_type: 'desktop',  
            // site_type_short: 'web', 
            // site_webProperty: 'nutrilite recommender',  
            // site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender',
        },
        questionnaire: 
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '',
                page_subCategory: 'targeted',
                site_country: 'br',
                site_currencyCode: 'brl',  
                site_language: 'pt',  
                // site_prefix: 'amway',
                // site_region: 'americas', 
                // site_subRegion: 'latam', 
                // site_type: 'desktop',  
                // site_type_short: 'web', 
                // site_webProperty: 'nutrilite recommender',  
                // site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender',
            },
        recommendations: {
            event_name: 'product_list_view',
            page_category: 'recommendations | Recomendador',  
            page_name: 'recommendations',
            page_section: 'recommendations',
            page_subCategory: 'targeted',
            product_id: [''],
            product_name: [''],
            site_country: 'br',
            site_currencyCode: 'brl', 
            site_language: 'pt',  
            // site_prefix: 'amway',
            // site_region: 'americas', 
            // site_subRegion: 'latam', 
            // site_type: 'desktop',  
            // site_type_short: 'web', 
            // site_webProperty: 'nutrilite recommender',  
            // site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender',  
        },
        RecommendationsContinue: {
            event_name: 'view_recommendations',  
        },
        ShareContinue:
        
                {
                event_name: 'share',  
                share_channel: '',
                },
        
        
    }
};
