export const environment = {
    utagInfo: {
        startQuestionnaire: {
            page_category: 'start-questionnaire | Recomendador',  
            page_name: 'start-questionnaire',
            page_section: 'home',
            page_subCategory: 'targeted',
            //continueAnswer: '',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'nutrilite recommender',  
            site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
        },
        howDoesItWork: {
            page_category: 'how-does-it-work | Recomendador',  
            page_name: 'how-does-it-work',
            page_section: 'how-does-it-work',
            page_subCategory: 'targeted',
            //continueAnswer: '',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'nutrilite recommender',  
            site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender',
        },
        questionnaire: [
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: 'country',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender',
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: 'questionnaire_start',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                //site_country: '',
                //site_currencyCode: '', 
                //site_language: 'es',  
                //site_prefix: 'amway',
                //site_region: 'americas', 
                //site_subRegion: 'latam', 
                //site_type: 'desktop',  
                //site_type_short: 'web', 
                //site_webProperty: 'nutrilite recommender',  
                //site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender',
            },            
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Eres-mujer-u-hombre?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender',
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Qué-edad-tienes?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Por-qué-te-concentras-en-tu-bienestar?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Consumes-actualmente-un-suplemento-alimenticio/dietario-con-vitaminas-y/o-minerales?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Qué-tipo-de-asesoría-sobre-suplementos-alimenticios/dietarios-prefieres?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Cuántas-frutas-y-vegetales-consumes-diariamente?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Cómo-describirías-tu-alimentación-actual?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: 'Cuando-te-despiertas-por-la-mañana,-¿Te-sientes-con-energía?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Cuántas-porciones-de-alimentos-ricos-en-calcio-consumes-diariamente?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Con-qué-frecuencia-haces-ejercicio-durante-la-semana?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Vives-o-trabajas-en-un-área-de-mucha-contaminación,-tráfico-pesado,-industrias-alrededor,-humo-o-aire-de-mala-calidad?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Estás-interesado(a)-en-tu-bienestar-digestivo?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Pasas-mucho-tiempo-frente-a-la-computadora/ordenador,-o-se-sienten-cansados-tus-ojos-al-final-del-día?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Te-dijo-tu-doctor-que-necesitas-más-hierro-en-tu-dieta?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Quieres-mantener-niveles-sanos-de-colesterol-y-triglicéridos,-además-de-promover-tu-bienestar-cardiovascular?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',   
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Cómo-describes-mejor-tu-exposición-al-sol-en-promedio-por-día?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: '¿Estás-interesado(a)-en-mantener-en-condiciones-normales-las-uñas,-el-cabello-y-la-piel?',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',   
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender',  
            },
            {
                page_category: 'questionnaire | Recomendador',  
                page_name: 'questionnaire',
                page_section: 'questionnaire_complete',
                page_subCategory: 'targeted',
                //continueAnswer: '',
                site_country: '',
                site_currencyCode: '',   
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'nutrilite recommender',  
                site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender',  
            },
        ],
        recommendations: {
            page_category: 'recommendations | Recomendador',  
            page_name: 'recommendations',
            page_section: 'recommendations',
            page_subCategory: 'targeted', 
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'nutrilite recommender',  
            site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender',  
        },
        QuestionnarieContinue: {
            event_name: 'continue',  
            page_section: '',
            continueAnswer: '',
        },
        RecommendationsContinue: {
            event_name: 'view_recommendations',  
        },
        ShareContinue: 
        [
            {
            event_name: 'share',  
            share_channel: '',
            },
            {
            event_name: 'share',  
            share_channel: '',
            },
            {
            event_name: 'share',  
            share_channel: '',
            },
            {
            event_name: 'share',  
            share_channel: '',
            },
        
        ],
        countries: {
            page_category: 'countries | Recomendador',  
            page_name: 'countries',
            page_section: 'countries',
            page_subCategory: 'targeted',
            continueAnswer: '',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'nutrilite recommender',  
            site_webProperty_mod: 'https://latinamway.com/recomendador | nutrilite recommender', 
        }
    }
};
