export const environment = {
    utagInfo: {
        home: {
            page_category: 'inicio | Recomendador',  
            page_name: 'inicio',
            page_section: 'inicio',
            page_subCategory: 'inicio',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        startQuestionnaire: {
            page_category: 'iniciar cuestionario | Recomendador',  
            page_name: 'iniciar cuestionario',
            page_section: 'iniciar cuestionario',
            page_subCategory: 'iniciar cuestionario',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        howDoesItWork: {
            page_category: 'como funciona | Recomendador',  
            page_name: 'como funciona',
            page_section: 'como funciona',
            page_subCategory: 'como funciona',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        questionnaire: {
            page_category: 'cuestionario | Recomendador',  
            page_name: 'cuestionario',
            page_section: 'cuestionario',
            page_subCategory: 'cuestionario',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        recommendations: {
            page_category: 'recomendaciones | Recomendador',  
            page_name: 'recomendaciones',
            page_section: 'recomendaciones',
            page_subCategory: 'recomendaciones',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        countries: {
            page_category: 'comprar | Recomendador',  
            page_name: 'comprar',
            page_section: 'comprar',
            page_subCategory: 'comprar',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        }
    }
};
