export const environment = {
    utagInfo: {
        startQuestionnaire: {
            page_category: 'Start questionarie | Recomendador',  
            page_name: 'Start questionarie',
            page_section: 'Start questionarie',
            page_subCategory: 'Start questionarie',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        howDoesItWork: {
            page_category: 'how does it works | Recomendador',  
            page_name: 'how does it works',
            page_section: 'how does it works',
            page_subCategory: 'how does it works',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        questionnaire: [
            {
                page_category: 'Country | Recomendador',  
                page_name: 'Country',
                page_section: 'Country',
                page_subCategory: 'Country',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {
                page_category: 'cuestionario | Recomendador',  
                page_name: 'cuestionario',
                page_section: 'cuestionario',
                page_subCategory: 'cuestionario',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {
                page_category: 'Gender | Recomendador',  
                page_name: 'Gender',
                page_section: 'Gender',
                page_subCategory: 'Gender',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {                    
                page_category: 'Age | Recomendador',  
                page_name: 'Age',
                page_section: 'Age',
                page_subCategory: 'Age',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 

            },
            {
                page_category: 'bienestar | Recomendador',  
                page_name: 'bienestar',
                page_section: 'bienestar',
                page_subCategory: 'bienestar',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {
                page_category: 'suplemento | Recomendador',  
                page_name: 'suplemento',
                page_section: 'suplemento',
                page_subCategory: 'suplemento',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {
                page_category: 'asesoría | Recomendador',  
                page_name: 'asesoría',
                page_section: 'asesoría',
                page_subCategory: 'asesoría',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {                    
                page_category: 'FrutasyVegetales | Recomendador',  
                page_name: 'FrutasyVegetales',
                page_section: 'FrutasyVegetales',
                page_subCategory: 'FrutasyVegetales',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 

            },
            {
                page_category: 'alimentación| Recomendador',  
                page_name: 'alimentación',
                page_section: 'alimentación',
                page_subCategory: 'alimentación',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {                    
                page_category: 'energía | Recomendador',  
                page_name: 'energía',
                page_section: 'energía',
                page_subCategory: 'energía',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 

            },
            {
                page_category: 'calcio | Recomendador',  
                page_name: 'calcio',
                page_section: 'calcio',
                page_subCategory: 'calcio',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {
                page_category: 'ejercicio | Recomendador',  
                page_name: 'ejercicio',
                page_section: 'ejercicio',
                page_subCategory: 'ejercicio',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {
                page_category: 'contaminación | Recomendador',  
                page_name: 'contaminación',
                page_section: 'contaminación',
                page_subCategory: 'contaminación',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {                    
                page_category: 'BienestarDigestivo | Recomendador',  
                page_name: 'BienestarDigestivo',
                page_section: 'BienestarDigestivo',
                page_subCategory: 'BienestarDigestivo',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 

            },
            {
                page_category: 'computadora | Recomendador',  
                page_name: 'computadora',
                page_section: 'computadora',
                page_subCategory: 'computadora',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {
                page_category: 'hierro | Recomendador',  
                page_name: 'hierro',
                page_section: 'hierro',
                page_subCategory: 'hierro',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {
                page_category: 'colesterol | Recomendador',  
                page_name: 'colesterol',
                page_section: 'colesterol',
                page_subCategory: 'colesterol',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {                    
                page_category: 'sol | Recomendador',  
                page_name: 'sol',
                page_section: 'sol',
                page_subCategory: 'sol',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 

            },
            {
                page_category: 'uñas | Recomendador',  
                page_name: 'uñas',
                page_section: 'uñas',
                page_subCategory: 'uñas',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
            },
            {                    
                page_category: 'BuenTrabajo | Recomendador',  
                page_name: 'BuenTrabajo',
                page_section: 'BuenTrabajo',
                page_subCategory: 'BuenTrabajo',
                //site_country: '',
                //site_currencyCode: '',  
                site_language: 'es',  
                site_prefix: 'amway',
                site_region: 'americas', 
                site_subRegion: 'latam', 
                site_type: 'desktop',  
                site_type_short: 'web', 
                site_webProperty: 'ecommerce',  
                site_webProperty_mod: 'www.amway.com.mx | ecommerce', 

            },
        
        ],
        recommendations: {
            page_category: 'recomendaciones | Recomendador',  
            page_name: 'recomendaciones',
            page_section: 'recomendaciones',
            page_subCategory: 'recomendaciones',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        countries: {
            page_category: 'comprar | Recomendador',  
            page_name: 'comprar',
            page_section: 'comprar',
            page_subCategory: 'comprar',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        }
    }
};
